### ISSUE TITLE
Global phased out should be sorted top but not pre selected

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#88]
Global phased out indicators should not be pre-selected in the global indicators. see screenshot below. 

Btw: I am testing updating the indicators in one of our test instances and importing categories ++ and data elements ++ and etc in batches. Just FYI in case something breaks I did just replace the old Theme with a equivalent one with a different UiD (updated in the settings app so that seems to work great!)
![global phased out.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ef989521838fe99fe1be50a159b09b3c52653f6b14b1247a80e03cfd183954570c4ba4100e584dada88f2bf7b63c72d95e0fbcd5695e66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3c26e08d8a463719031b89ed10.PNG)

**Comment by tokland** [comment]
Done: https://github.com/EyeSeeTea/dataset-configuration/pull/219

Only active data elements / indicators can be preselected

**Comment by troyel** [comment]
This is still an issue with outcomes - the phased out  are pre marked.
![phased out otcomes.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46f89c9b308787e980fcab03ab49f39b244334316546b3397f8fe62bab0021435a571da949090943f5a8d82da6e73c70880f09e980695b75d42103eee9dc4be05ce36ade0d97bcae8b44cae93824e28b89463e1f051b81fb4f78.PNG)

**Comment by tokland** [comment]
Sorry for the confusion Troyel, this code is not in 0.7.1, it was done after the release, will be available on the next one.
